graph TD;
    test_tasks_api["test_tasks_api.py"];
    check_env["check_env.py"];
    gesture_spotify_player["gesture_spotify_player.py"];
    app["app.py"];
    server["server.py"];
    debug_mp["debug_mp.py"];
    generate_tone["generate_tone.py"];
    Client --> server;